sonar.projectKey=pooker-frontend
sonar.projectName=Pooker - Frontend
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/looker/lcov.info
