spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://localhost:5432/trabalho_if
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=false
server.port=8081
jwt.secret=${JWT_SECRET:0e1110b29e5cab1d172a006d08b8c7c1c4225c039e213dc14ce1cf1675d3e9f3}