sonar.projectKey=pooker-payment-service
sonar.projectName=Pooker - Payment Service
sonar.sources=app
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.exclusions=**/__pycache__/**
