sonar.projectKey=pooker-api-gateway
sonar.projectName=Pooker - API Gateway
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main
sonar.java.test.binaries=build/classes/java/test
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.exclusions=**/generated/**,**/*.spec.ts
