sonar.projectKey=pooker-alugueis-service
sonar.projectName=Pooker - Alugueis Service
sonar.sources=app
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
sonar.exclusions=**/alembic/**,**/__pycache__/**
