spring.application.name=api-gateway
spring.main.web-application-type=reactive
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
logging.level.org.springframework.security=DEBUG
jwt.secret=${JWT_SECRET:0e1110b29e5cab1d172a006d08b8c7c1c4225c039e213dc14ce1cf1675d3e9f3}
