"""recria a tabela filmes com todos os campos

Revision ID: 39dd8a920b45
Revises: ce013543f3df
Create Date: 2025-08-19 23:54:10.501799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39dd8a920b45'
down_revision: Union[str, Sequence[str], None] = 'ce013543f3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('sinopse', sa.Text(), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=True),
    sa.Column('elenco', sa.String(length=255), nullable=True),
    sa.Column('diretor', sa.String(length=100), nullable=True),
    sa.Column('classificacao_indicativa', sa.String(length=20), nullable=True),
    sa.Column('data_lancamento', sa.Date(), nullable=True),
    sa.Column('preco_aluguel', sa.Float(), nullable=True),
    sa.Column('total_copias', sa.Integer(), nullable=True),
    sa.Column('copias_disponiveis', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filmes_id'), 'filmes', ['id'], unique=False)
    op.create_index(op.f('ix_filmes_titulo'), 'filmes', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filmes_titulo'), table_name='filmes')
    op.drop_index(op.f('ix_filmes_id'), table_name='filmes')
    op.drop_table('filmes')
    # ### end Alembic commands ###
