"""Your descriptive message for the migration

Revision ID: 8c0a449e9a6d
Revises: cd75cfc5ea2c
Create Date: 2025-08-26 23:20:56.213388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c0a449e9a6d'
down_revision: Union[str, Sequence[str], None] = 'cd75cfc5ea2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version_usuario')
    op.drop_index(op.f('ix_alugueis_id'), table_name='alugueis')
    op.drop_table('alugueis')
    op.drop_index(op.f('ix_tb_usuarios_id'), table_name='tb_usuarios')
    op.drop_table('tb_usuarios')
    op.drop_table('alembic_version_alugueis')
    op.add_column('filmes', sa.Column('sinopse', sa.Text(), nullable=True))
    op.add_column('filmes', sa.Column('imagem_url', sa.String(length=255), nullable=True))
    op.add_column('filmes', sa.Column('duracao_minutos', sa.Integer(), nullable=True))
    op.add_column('filmes', sa.Column('elenco', sa.String(length=255), nullable=True))
    op.add_column('filmes', sa.Column('diretor', sa.String(length=100), nullable=True))
    op.add_column('filmes', sa.Column('classificacao_indicativa', sa.String(length=20), nullable=True))
    op.add_column('filmes', sa.Column('data_lancamento', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filmes', 'data_lancamento')
    op.drop_column('filmes', 'classificacao_indicativa')
    op.drop_column('filmes', 'diretor')
    op.drop_column('filmes', 'elenco')
    op.drop_column('filmes', 'duracao_minutos')
    op.drop_column('filmes', 'imagem_url')
    op.drop_column('filmes', 'sinopse')
    op.create_table('alembic_version_alugueis',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_alugueis_pkc'))
    )
    op.create_table('tb_usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('senha', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('data_nascimento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('admin', 'user', name='role_enum'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tb_usuarios_pkey')),
    sa.UniqueConstraint('cpf', name=op.f('tb_usuarios_cpf_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('email', name=op.f('tb_usuarios_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tb_usuarios_id'), 'tb_usuarios', ['id'], unique=False)
    op.create_table('alugueis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filme_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_aluguel', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('data_prevista_devolucao', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('data_devolucao', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('valor_aluguel', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ATIVO', 'DEVOLVIDO', 'ATRASADO', name='aluguelstatus'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('alugueis_pkey'))
    )
    op.create_index(op.f('ix_alugueis_id'), 'alugueis', ['id'], unique=False)
    op.create_table('alembic_version_usuario',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_usuario_pkc'))
    )
    # ### end Alembic commands ###
