"""adiciona novas infos aos filmes

Revision ID: ce013543f3df
Revises: b7baef00f196
Create Date: 2025-08-19 23:51:02.373566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce013543f3df'
down_revision: Union[str, Sequence[str], None] = 'b7baef00f196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filmes_id'), table_name='filmes')
    op.drop_index(op.f('ix_filmes_titulo'), table_name='filmes')
    op.drop_table('filmes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genero', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ano', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preco_aluguel', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_copias', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('copias_disponiveis', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('filmes_pkey'))
    )
    op.create_index(op.f('ix_filmes_titulo'), 'filmes', ['titulo'], unique=False)
    op.create_index(op.f('ix_filmes_id'), 'filmes', ['id'], unique=False)
    # ### end Alembic commands ###
